name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      C: gcc-9
      CXX: g++-9
    steps:
      - uses: actions/checkout@v2
      - name: clear iptables
        id: clear_iptables
        continue-on-error: true
        run: |
          sudo iptables -P INPUT ACCEPT
          sudo iptables -P FORWARD ACCEPT
          sudo iptables -P OUTPUT ACCEPT
          sudo iptables -t nat -F
          sudo iptables -t mangle -F
          sudo iptables -F
          sudo iptables -X
      - name: install dependencies
        run: |
          sudo apt install -y g++-9 gcc-9
          sudo apt install -y doxygen libpcap-dev
          # The version is not compatible, waiting for Ubuntu 20.04
          # sudo apt install -y libspdlog-dev
          git clone https://github.com/gabime/spdlog.git
          cd spdlog && mkdir build && cd build
          cmake .. && make -j
          sudo make install
      - name: setup
        run: |
          mkdir build
          cd build
          cmake ..
      - name: make
        run: |
          cd build
          make -j
      - name: check
        if: ${{ steps.clear_iptables.outcome == 'success' }}
        continue-on-error: true
        run: |
          cd build
          make check
      - name: benchmark
        continue-on-error: true
        run: |
          cd build
          apps/tcp_benchmark
